default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: happiness_trend_developement

test:
  <<: *default
  host: <%= ENV.fetch('PGHOST', '127.0.0.1') %>
  user: <%= ENV.fetch('PGUSER', 'hieunguyen') %>
  database: <%= ENV.fetch('POSTGRES_DB', 'happiness_trend_test') %>

production:
  <<: *default
  database: happiness_trend_production
  user: tinypulse
